### ISSUE TITLE
Traduction "Welcome"

### ISSUE THREAD

**Issue by MathildeMousset** [appliedepi/epiRhandbook_fr#2]
J'ai commencé la [page d'accueil]( https://github.com/appliedepi/epiRhandbook_fr/blob/master/index.Rmd).

**TODO**
- [ ] Le titre (et toutes les fois que le titre est cité)
- [ ] Les liens vers les autres chapitres

**Questions**
Devrais-je traduire les noms des départements américains dans les remerciements ? j'aurais tendance à dire non, que ça n'a pas de sens, mais bon, c'est discutable.

**Comment by MathildeMousset** [comment]
Pour note : le chapitre fait lien vers les titres suivants dans le script data_used.Rmd
- Download handbook and data  {#download_book_data}
- Download offline handbook  {#download_offline}

- [ ] Il faudra vérifier, quand le chapitre data_used.Rmd sera traduit, que le titre est référé correctement dans l'index.
